# Change these first
owner: soroco
repo: statuspage
user-agent: kfiles

sites:
  - name: Soroco Azure Cloud
    url: https://www.google.com
  - name: Cluster eastus1-lts
    url: https://en.wikipedia.org
  - name: Scout Portal
    url: https://news.ycombinator.com
  - name: PostgreSQL DB
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: statuspage.soroco.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/soroco/statuspage/master/assets/upptime-icon.svg
  name: Soroco Status
  introTitle: "**Scout Status** for Soroco customer cluster"
  introMessage: "Status updated every 5 minutes"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
